apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  name: production-cluster
spec:
  displayName: Production Cluster
  clusterSpec:
    rkeConfig:
      network:
        plugin: canal

# 2021-07-26 - config: Cleanup old configurations
