apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: production-cluster
  git:
    syncRepo: https://github.com/yourorg/gitops-repo
    syncBranch: main
    policyDir: "/"
  sourceFormat: hierarchy

# 2021-05-06 - ci: Configure multi-cluster tests

# 2021-04-20 - ci: Update cluster sync pipeline

# 2021-06-29 - docs: Update documentation

# 2021-02-01 - fix: Correct network configuration

# 2021-02-26 - docs: Update documentation

# 2021-03-12 - config: Update documentation
