apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: production-cluster
  git:
    syncRepo: https://github.com/yourorg/gitops-repo
    syncBranch: main
    policyDir: "/"
  sourceFormat: hierarchy

# 2021-02-04 - feat: Add new cluster configuration

# 2021-07-16 - feat: Implement Rancher monitoring
