name: Cluster Configuration Sync
on:
  push:
    branches: [ main ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
      - name: Apply manifests
        run: kubectl apply -f manifests/

# 2021-07-21 - ci: Add health check workflow

# 2021-05-10 - docs: Update documentation

# 2021-06-14 - config: Update documentation

# 2021-07-13 - chore: Update documentation

# 2021-03-18 - config: Update documentation

# 2021-05-31 - chore: Cleanup old configurations

# 2021-06-02 - feat: Create Anthos sync policy

# 2021-04-23 - chore: Refactor cluster manifests

# 2021-01-04 - ci: Update cluster sync pipeline

# 2021-03-31 - fix: Correct network configuration

# 2021-06-23 - feat: Add new cluster configuration
